### ISSUE TITLE
Delete History

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [Ayyoub-ESSADEQ/chatgpt-connect#1]
Hello I have some ideas to improve your amazing extension. It's little bit borring to always go and connect on chrome but i understand how amazing it is.

- Delete History
- increase font size of output
- have a button with some custom pre saved text : "i am a dev in javascript, typescript try improve this code and tell me errors......"

**Comment by Ayyoub-ESSADEQ** [comment]
@jojojojojoj5564656465465  are you tallking about the popup screen of the chrome extension ?

**Comment by Ayyoub-ESSADEQ** [comment]
This issue is not related to chatgpt-connect, It's related to Cocaptain vscode extension make sure to refer to its respository https://github.com/Ayyoub-ESSADEQ/cocaptain/issues.
